# Tracing if resources are closed/released correctly.
jvm.resource.tracing=true
disable.resource.warning=false
check.thread.safety=true
disable.discard.warning=false
# for profiling
jvm.safepoint.enabled=false
# temporary option
warnAndCloseIfNotClosed=true
# wire.generate.v2=false
# reduce logging of the announcer
chronicle.announcer.disable=true
dumpCodeToTarget=true
compiler.options=
# to be removed in x.26
class.not.found.for.missing.class.alias=true